# Generated by Django 3.2.15 on 2022-08-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('sno', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
