# Generated by Django 3.2.15 on 2022-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
